### ISSUE TITLE
優化請求。

### ISSUE THREAD

**Issue by YheonYeung** [kuoruan/dmhy-download-helper#144]
Hi, 第一次用你的腳本，我不太懂，有些小問題想反饋一下。
動漫花園一直在用一個樣式[https://userstyles.org/styles/133936/acg-bt](url)，但是裝上這邊的腳本之後，整個排版亂掉了，不用美化樣式就沒事。
所以想問問能不能改不衝突這樣，如果不方便的話就算喇。
![image](https://i.imgur.com/WdLHHus.png)
![image](https://i.imgur.com/5aJCW6I.png)
![image](https://i.imgur.com/FwKfQSH.png)

**Comment by kuoruan** [comment]
你给的那个样式是根据列表列数来做样式选择器的
由于我的脚本会向列表中插入多余的列，就造成了样式错乱
当前无解决方案
