### ISSUE TITLE
网站原生的排序功能（比如按种子数排序）被无效化

### ISSUE THREAD

**Issue by gsxgmpkt9020** [kuoruan/dmhy-download-helper#187]
网站自身的排序功能（比如按种子数排序，下旧番冷番很有用）被无效化

可能与“ 列表链接批量复制”的实现方式有冲突。

但我个人的场景用不到“ 列表链接批量复制”的功能，但是需要原生的列表排序功能。

建议加个功能开关（比如脚本里true false之类）或者利用monkey类扩展的UI开关.

或者把“列表页下载 torrent 文件”单独另做一个脚本以与排序兼容

希望能考虑下这个需求，感激不尽

**Comment by kuoruan** [comment]
OK，我检查一下
